version: "3"

services:
  flipflapp:
    image: docker.uibk.ac.at:443/informatik/qe/sepsss21/group3/g3t1/flipflapp:1.2.0
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://flipflapp-db:3306/timeguess
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - flipflapp-db

  flipflapp-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: timeguess
      MYSQL_USER: timeguess
      MYSQL_PASSWORD: password
    volumes:
      - flipflapp-db:/var/lib/mysql

volumes:
  flipflapp-db:
